### ISSUE TITLE
not an argument still a virus

### ISSUE THREAD

**Issue by TheCuteOwl** [Siegerz/BlitzedGrabberV12#1]

**Comment by Siegerz** [comment]
Who Would Of Thought

**Comment by TheCuteOwl** [comment]
that's not a valid argument for virus

**Comment by Siegerz** [comment]
i Think You Might Be Mistaken For The Grabber In Resources

**Comment by TheCuteOwl** [comment]
Haha, i know you use ORCUS

**Comment by TheCuteOwl** [comment]
don't try to lie

**Comment by Siegerz** [comment]
Orcus Is The Framework For The Grabber,

**Comment by Siegerz** [comment]
Stay In SInagpore Hiwong

**Comment by TheCuteOwl** [comment]
I'm not in singapore

**Comment by TheCuteOwl** [comment]
and why it would take that much time to load for only a framework

**Comment by TheCuteOwl** [comment]
because ORCUS is launched and then the program showed up

**Comment by Siegerz** [comment]
I Bet Your Parents Taught You Witch Craft You Freaky Enthuisiast Abomination Fuck

**Comment by Siegerz** [comment]
Dumb Fuck

Amazin

**Comment by Siegerz** [comment]
Amazin

**Comment by TheCuteOwl** [comment]
I love dog wouaf
